### ISSUE TITLE
CodePush support out of box

### ISSUE THREAD

**Issue by retyui** [Instabug/Instabug-React-Native#838] opened 2022-11-29 14:51 UTC
### Steps to Reproduce the Problem

Use codepush to apply an over-the-air update to existing app binary and cause a crash. You'll notice the previously uploaded JS source map (for the existing app binary) does not map the stack trace correctly.

### Expected Behavior

Need add ability to match JS bundle version and uploaded source maps  

### Actual Behavior

we see broken stack trace:

![image](https://user-images.githubusercontent.com/4661784/204561349-564ac506-592c-4e4f-ad69-8b8e60e0a66d.png)

### Instabug integration code

no

### SDK Version

all

### React Native, iOS and Android Versions

all

### Device Model

all

----

> please add it immediately or we have to replace Instabug with Sentry

**Comment by DavidMina96** [comment] 2022-12-04 15:00
Duplicate of #656 

Hi @retyui, 

Thank you for reporting this. We can surely imagine the value of adding CodePush support for our users, and indeed, I assure you we're sparing no effort to make it available in one of our upcoming releases soon.

**Comment by a7medev** [comment] 2024-09-30 08:58
Closing this since we already support Code Push since v12.6.0. Please refer to our [documentation for information on integrating Instabug with Code Push](https://docs.instabug.com/docs/codepush-for-react-native).

**Closed by a7medev** 2024-09-30 08:58 UTC
Labels: Planned
