### ISSUE TITLE
I have problem to read my sqlite data

### ISSUE THREAD

**Issue by sinakiani88** [Instabug/Instabug-React-Native#550] opened 2021-02-07 13:37 UTC
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1294 SQLITE_CANTOPEN_ENOENT[1294]): Could not open database
![1](https://user-images.githubusercontent.com/76960433/107148133-dd945a80-6966-11eb-9822-ec8ce11e02fe.jpg)

**Comment by AliAbdelfattah** [comment] 2021-02-07 16:48
Hi @sinakiani88, thanks for your report. I'm not sure this is being caused by Instabug, could you please double-check and if so post the full stack trace?

These SoF questions might give you an idea of what's going wrong, I hope it helps.
https://stackoverflow.com/questions/65256201/android-cannot-open-my-database-from-assets
https://stackoverflow.com/questions/52053932/specified-directory-or-database-file-does-not-exist

**Comment by sinakiani88** [comment] 2021-02-07 17:17
> Hi @sinakiani88, thanks for your report. I'm not sure this is being caused by Instabug, could you please double-check and if so post the full stack trace?
> 
> These SoF questions might give you an idea of what's going wrong, I hope it helps.
> https://stackoverflow.com/questions/65256201/android-cannot-open-my-database-from-assets
> https://stackoverflow.com/questions/52053932/specified-directory-or-database-file-does-not-exist

actually it could not help me

**Comment by AliAbdelfattah** [comment] 2021-03-03 11:26
Closing the issue. Please feel free to reopen if you were able to find logs related to Instabug.

**Closed by AliAbdelfattah** 2021-03-03 11:26 UTC
