### ISSUE TITLE
Instabug.start(...) does not recognize token as a variable

### ISSUE THREAD

**Issue by rafalzawadzki** [Instabug/Instabug-React-Native#396] opened 2019-09-13 11:05 UTC
### Steps to Reproduce the Problem
Integrate Instabug.

### Expected Behavior
I can use a constant instead of a string to provide the Instabug token, like this:
`Instabug.start(Constants.INSTABUG_TOKEN, [Instabug.invocationEvent.shake]);`

### Actual Behavior
I receive a build error while building Android project:
`Instabug: err: INSTABUG_APP_TOKEN not found. Make sure you've added the SDK initialization line Instabug.start Or added the environment variable INSTABUG_APP_TOKEN`

I think that line of code is the culprit: 
https://github.com/Instabug/Instabug-React-Native/blob/master/android/upload_sourcemap.sh#L14

### Instabug integration code
`Instabug.start(Constants.INSTABUG_TOKEN, [Instabug.invocationEvent.shake]);`

### SDK Version
8.6.3

**Comment by alyezz** [comment] 2019-09-13 11:44
@rafalzawadzki The error you are getting is from the script that automatically generates and uploads the sourcemap files to your dashboard for crash symbolication. You can simply add `INSTABUG_APP_TOKEN` as an environment variable with your token.

**Comment by alyezz** [comment] 2019-09-16 04:42
@rafalzawadzki I will close this now feel free to re-open if you have any questions

**Comment by jacquesdev** [comment] 2019-09-19 22:50
@alyezz - in the example above, @rafalzawadzki is in fact doing one of the options mentioned in the feedback, `Make sure you've added the SDK initialization line Instabug.start Or added the environment variable INSTABUG_APP_TOKEN`

So they have added it to the SDK initialization, but it's not working, and not sure why you are suggesting adding it to the environment.

**Comment by alyezz** [comment] 2019-09-19 22:58
@jacqueesdev the script works by looking for the token in the project files and matching to an expression. The expression to be matched requires that the token be written in the same line as the initialization `Instabug.start("example-token", ..`, so in this case he added a constant that contains the token and not the token itself, therefore the script was not able to automatically detect the token.

**Comment by jacquesdev** [comment] 2019-09-19 23:02
Can you improve the script so that it's not necessary? Because you are essentially asking users to then preferably store the actual token in the source which is not a good practice. I understand you can set an env variable, but realistically that does not sound like a good solution?

**Comment by alyezz** [comment] 2019-09-19 23:08
@jacquesdev you are definitely correct there is always room for improvement here. We try as much as we can to come up with a script that works for everyone. The token may be stored in a separate file with other tokens, in constants or maybe substituted  at build/runtime depending on each user's setup and environment. If you have any improvements in mind feel free to create a PR with it and we'd be happy to merge it :)

**Comment by rafalzawadzki** [comment] 2019-09-20 08:10
@alyezz Please at least make the error more informative... I've wasted almost an hour going through your docs & code, trying to understand why something so trivial does not work. 

Figured it totally by accident with a disbelieving: `noooo, they *seriously* did that this way!` on my lips.

Should say:
`INSTABUG_APP_TOKEN not found. Make sure you've added the SDK initialization line Instabug.start *(while not using a variable/constant, but with the value explicitly declared)* Or added the environment variable INSTABUG_APP_TOKEN`

**Comment by HeshamMegid** [comment] 2019-09-22 09:47
@rafalzawadzki the error message could definitely be clearer. We'll change it to something more descriptive.

Thanks!

**Closed** 2019-09-22 09:55 UTC

**Comment by newah** [comment] 2019-10-02 08:32
@alyezz  adding INSTABUG_APP_TOKEN in my .env file didn't work. also, I have different tokens for ios/android.

and how is this not enough?
```
task upload_sourcemap(type: Exec) {
    environment "INSTABUG_APP_TOKEN", project.env.get("INSTABUG_KEY_ANDROID")
    commandLine 'sh', './upload_sourcemap.sh'
}
```

**Comment by HeshamMegid** [comment] 2019-10-08 15:02
@newah we've missed your reply since the issue is closed. I've your reply to a new issue (#417) so we could continue the discussion there.
