### ISSUE TITLE
Instabug modal will not close on Android

### ISSUE THREAD

**Issue by jack-mullen** [Instabug/Instabug-React-Native#219] opened 2018-11-12 17:10 UTC
### Steps to Reproduce the Problem

1. Invoke Instabug's feedback form `BugReporting.invoke()`
2. Tap either "Report a Problem" or "Suggest an Improvement"
3. Tap the 'X' in the top left corner to close the window, and tap "discard"

At this point the alert will close but the Instabug window/application will still be present, and attempting to submit the report or add/remove attachments/images will cause the following:

`Attempt to invoke virtual method 'java.util.List com.instabug.bug.model.Bug.e()' on a null object reference`

### Expected Behavior

When tapping "discard", Instabug should close and return the user to the application.

### Actual Behavior

When tapping "discard", the alert dialog closes but Instabug still persists. There is no way to exit from Instabug apart from closing the entire application. 

### Instabug integration code
**App.js**
```
Instabug.startWithToken('TOKEN', [Instabug.invocationEvent.none])
Instabug.setPrimaryColor(processColor('#ff0099'))
Instabug.setIntroMessageEnabled(false)
Instabug.setPromptOptionsEnabled(false, true, true)
Instabug.setChatNotificationEnabled(false)
Instabug.setViewHierarchyEnabled(false)
```

### SDK Version

instabug-reactnative: 8.0.17

### React Native, iOS and Android Versions

React: 16.6.1
React Native: 0.57.4
Android version: 8.0.0

### Device Model

Tested on a physical device: OnePlus 3T (A3003)
Tested on emulated devices: Pixel 2 & Nexus 6

This only seems to affect Android, multiple tests on iOS have worked fine.

**Comment by salmamali** [comment] 2018-11-25 09:44
Hello @jack-mullen ,
This issue occurs because there are multiple instances of Instabug. We will be working on a way to make sure that does not happen. If you have a sample app that has this issue, it would be very helpful if you share it with us.

**Comment by HeshamMegid** [comment] 2018-12-10 09:57
@jack-mullen, as @salmamali mentioned, we're working on making sure this doesn't happen, so I'll close this issue for now.

If you manage to create a sample app that reproduces this issue, that will help us tremendously.

**Closed** 2018-12-10 09:58 UTC
