### ISSUE TITLE
React Native 0.60 rnpm and autolinking issues

### ISSUE THREAD

**Issue by Jaraujo6** [Instabug/Instabug-React-Native#319] opened 2019-07-08 16:21 UTC
### Steps to Reproduce the Problem
run ```npm i react-native@latest``` to upgrade to react native 0.60
then run ```react-native run-android```

### Expected Behavior
app will open

### Actual Behavior
compile error:
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - instabug-reactnative: https://github.com/Instabug/instabug-reactnative#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - @react-native-community/async-storage (to unlink run: "react-native unlink @react-native-community/async-storage")
  - instabug-reactnative (to unlink run: "react-native unlink instabug-reactnative")
```

### Instabug integration code

new RNInstabugReactnativePackage.Builder("token",MainApplication.this)
            .setInvocationEvent("button")
            .setPrimaryColor("#1D82DC")
            .setFloatingEdge("left")
            .setFloatingButtonOffsetFromTop(250)
            .build(),

### SDK Version

8.4.2

### React Native, iOS and Android Versions
react native 0.60

### Device Model

N/A

### [Optional] Project That Reproduces the Issue

N/A

**Comment by alyezz** [comment] 2019-07-10 15:19
@Jaraujo6 we are currently looking into this, in the mean time can you please send us the complete stack trace

**Comment by Jaraujo6** [comment] 2019-07-10 16:17
Thanks for your assistance @alyezz !
Unfortunately there is no stack trace. The both warnings appear immediate after running ```react-native run-android``.

**Comment by alyezz** [comment] 2019-07-11 21:22
Duplicate of #321

**Closed by alyezz** 2019-07-11 21:22 UTC
