### ISSUE TITLE
Network logs have a response body as string not a JSON 

### ISSUE THREAD

**Issue by davydspotnana** [Instabug/Instabug-React-Native#993] opened 2023-06-13 14:34 UTC
### Steps to Reproduce the Problem

1. use the latest `11.x` version of `instabug-reactnative` 
2. make a couple `https` req and then report an error

### Expected Behavior

`Response.Body` should be JSON not a string (like a `Request.body` on screenshot below)

### Actual Behavior

![111](https://github.com/Instabug/Instabug-React-Native/assets/95620376/562be38a-4dbf-4ce5-ac4c-05c4a098a7ac)

### Instabug integration code

...

### SDK Version

the latest

### React Native, iOS and Android Versions

RN `0.70`
iOS SDK: `true`
Android SDK: `true`

### Device Model

any device

-----

Links
- https://github.com/Instabug/Instabug-React-Native/blob/1be68a45215fcc6715110d23c921c137fd4ba4f2/src/modules/NetworkLogger.ts#L33-L38
- https://github.com/Instabug/Instabug-React-Native/blob/1be68a45215fcc6715110d23c921c137fd4ba4f2/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java#L940

**Comment by a7medev** [comment] 2023-06-16 11:22
Hi @davydspotnana! Thanks for reporting this issue and providing these details.
Can you please provide the response headers of that network log (specifically the `content-type` header)?

**Comment by davydspotnana** [comment] 2023-06-16 13:25
`content-type` is correct @a7medev 

![image](https://github.com/Instabug/Instabug-React-Native/assets/95620376/c62c1535-5ee0-4455-ae0d-de8ce3d83020)

**Comment by a7medev** [comment] 2023-06-16 13:36
@davydspotnana Can you send the request again and `console.log` the response from JavaScript? I'm suspecting that the JSON returned from the API is stringified and wrapped in another string.

**Comment by davydspotnana** [comment] 2023-06-16 15:17
yes you right:

```js
{
  contentType: 'application/json',
  duration: 417,
  errorCode: 0,
  errorDomain: '',
  method: 'GET',
  requestBody: '',
  requestBodySize: 0,
  requestContentType: '',
  requestHeaders: {
    Accept: 'application/json, text/plain, */*',
    Authorization: '<removed_by_security_reason>',
    'XXXXXXXX-e2e-headers': '{"userId":"415277ff-8fc3-4a9d-8167-cdb616a45b5a"}',
    'XXXXXXXX-traveler-info':
      '{"userOrgId":{"userId":{"id":"7011dcc7-645b-48c6-91ae-0b88bbb0ffbc"},"organizationId":{"id":"ecc5b835-8001-430c-98f8-fedeccebe4cf"},"agencyId":"","organizationAgencyId":{"id":"ecc5b835-8001-430c-98f8-fedeccebe4cf"},"tmcInfo":{"id":{"id":"ecc5b835-8001-430c-98f8-fedeccebe4cf"},"primaryServiceProviderTmc":{"tmcId":{"id":"ecc5b835-8001-430c-98f8-fedeccebe4cf"}},"secondaryServiceProviderTmcs":[],"metaData":{"name":"Spotnana Technology"}},"tmcBasicInfo":{"contractingTmc":{"id":{"id":"ecc5b835-8001-430c-98f8-fedeccebe4cf"},"name":""},"bookingTmc":{"id":{"id":"ecc5b835-8001-430c-98f8-fedeccebe4cf"},"name":"Spotnana Technology"}}},"preferences":{"preferredCurrency":"USD"}}',
    'x-app-platform': 'ios',
    'x-app-type': 'mobile',
    'x-app-version': '0.0.1',
    'x-session-id': '5d69d36f-8089-4b36-8c13-c5055617109a',
  },
  responseBody:
    '"{\\n  \\"airports\\": [{\\n    \\"airportName\\": \\"San Francisco International Airport\\",\\n    \\"airportCode\\": \\"SFO\\",\\n    \\"cityCode\\": \\"SFO\\",\\n    \\"location\\": {\\n      \\"name\\": \\"San Francisco\\",\\n      \\"stateName\\": \\"California\\",\\n      \\"countryName\\": \\"United States\\",\\n      \\"countryCode\\": \\"US\\",\\n      \\"latlong\\": {\\n        \\"latitude\\": 37.618999481,\\n        \\"longitude\\": -122.375\\n      },\\n      \\"googlePlaceId\\": \\"\\"\\n    }\\n  }, {\\n    \\"airportName\\": \\"Charles M. Schulz–Sonoma County Airport\\",\\n    \\"airportCode\\": \\"STS\\",\\n    \\"cityCode\\": \\"STS\\",\\n    \\"location\\": {\\n      \\"name\\": \\"Santa Rosa\\",\\n      \\"stateName\\": \\"California\\",\\n      \\"countryName\\": \\"United States\\",\\n      \\"countryCode\\": \\"US\\",\\n      \\"latlong\\": {\\n        \\"latitude\\": 38.50899887,\\n        \\"longitude\\": -122.8130035\\n      },\\n      \\"googlePlaceId\\": \\"\\"\\n    }\\n  }, {\\n    \\"airportName\\": \\"Oakland International Airport\\",\\n    \\"airportCode\\": \\"OAK\\",\\n    \\"cityCode\\": \\"OAK\\",\\n    \\"location\\": {\\n      \\"name\\": \\"Oakland\\",\\n      \\"stateName\\": \\"California\\",\\n      \\"countryName\\": \\"United States\\",\\n      \\"countryCode\\": \\"US\\",\\n      \\"latlong\\": {\\n        \\"latitude\\": 37.721298,\\n        \\"longitude\\": -122.221001\\n      },\\n      \\"googlePlaceId\\": \\"\\"\\n    }\\n  }, {\\n    \\"airportName\\": \\"Norman Y. Mineta San Jose International Airport\\",\\n    \\"airportCode\\": \\"SJC\\",\\n    \\"cityCode\\": \\"SJC\\",\\n    \\"location\\": {\\n      \\"name\\": \\"San Jose\\",\\n      \\"stateName\\": \\"California\\",\\n      \\"countryName\\": \\"United States\\",\\n      \\"countryCode\\": \\"US\\",\\n      \\"latlong\\": {\\n        \\"latitude\\": 37.362598,\\n        \\"longitude\\": -121.929001\\n      },\\n      \\"googlePlaceId\\": \\"\\"\\n    }\\n  }],\\n  \\"locations\\": [],\\n  \\"hotels\\": [],\\n  \\"poi\\": [],\\n  \\"railStations\\": [],\\n  \\"others\\": [],\\n  \\"googleSessionToken\\": \\"\\",\\n  \\"offices\\": [],\\n  \\"userBasicInfos\\": [],\\n  \\"tripBasicInfos\\": [],\\n  \\"carVendors\\": []\\n}"',
  responseBodySize: 2014,
  responseCode: 200,
  responseHeaders: {
    '': undefined,
    'cache-control': ' no-store',
    connection: ' keep-alive',
    'content-encoding': ' gzip',
    'content-type': ' application/json',
    date: ' Fri, 16 Jun 2023 15:11:25 GMT',
    'debug-tool-link':
      ' https://debug-stage.services.XXXXXXXX.com/file-search-results/ae15b63f22ea08c3_ae15b63f22ea08c3?q=debugid',
    pragma: ' no-cache',
    'set-cookie':
      ' AWSALB=pLU3YxSqfhVBYu76K+uUwszrU12b5qG6X3Uqh6uQGnW5bfrBRfT6CPTnEJrndNVgtdJZ7pQ664EvW8c7pFwDMwTG54v9xGK1X2Kuq5TJ+2IpQy54IbZs6r+QHMgT; Expires=Fri, 23 Jun 2023 15:11:25 GMT; Path=/, AWSALBCORS=pLU3YxSqfhVBYu76K+uUwszrU12b5qG6X3Uqh6uQGnW5bfrBRfT6CPTnEJrndNVgtdJZ7pQ664EvW8c7pFwDMwTG54v9xGK1X2Kuq5TJ+2IpQy54IbZs6r+QHMgT; Expires=Fri, 23 Jun 2023 15:11:25 GMT; Path=/; SameSite=None; Secure',
    'transfer-encoding': ' Identity',
    vary: ' origin,access-control-request-method,access-control-request-headers,accept-encoding',
  },
  serverErrorMessage: '',
  startTime: 1686928284940,
  url: 'https://master-internal-stage.XXXXXXXX.com/v1/air-autocomplete?query=Sfo',
};
```

**Comment by a7medev** [comment] 2023-06-16 16:06
@davydspotnana Given the response you sent, this is the expected behavior since the _parsed_ version of the `responseBody` is also a string (even though this string contains JSON format, the first parsing process produces a string in the end).
I'm closing this issue since it's not an issue from our side. 🙏🏼

**Closed by a7medev** 2023-06-16 16:06 UTC
