### ISSUE TITLE
duplicate method setEnabledAttachmentTypes on InstabugModule

### ISSUE THREAD

**Issue by RZulfikri** [Instabug/Instabug-React-Native#262] opened 2019-03-28 05:45 UTC
Hi check this, it have 3 same setEnabledAttachmentTypes method.

https://github.com/Instabug/Instabug-React-Native/blob/c40f46bdde162a367671d19eba4c0f05ca4f7287/android/src/main/java/com/instabug/reactlibrary/RNInstabugReactnativeModule.java#L553

**Comment by soumyamishra89** [comment] 2019-03-28 14:07
This is annoying. These are compilation errors and should not have been committed without checking.
Also InstabugCustomTextPlaceHolder.Key.SURVEYS_CUSTOM_THANKS_TITLE, 
InstabugCustomTextPlaceHolder.Key.SURVEYS_CUSTOM_THANKS_SUBTITLE,
InstabugCustomTextPlaceHolder.Key.SURVEYS_STORE_RATING_THANKS_TITLE,
InstabugCustomTextPlaceHolder.Key.SURVEYS_STORE_RATING_THANKS_SUBTITLE

cannot be resolved

**Comment by HeshamMegid** [comment] 2019-03-28 14:47
Thanks for reporting that. We're working on it and will release a fix ASAP.

**Comment by salmamali** [comment] 2019-03-28 15:28
We will be releasing the fix for `setEnabledAttachmentTypes` being added several times shortly. However, regarding the keys that cannot be resolved we cannot reproduce this issue, it could be that your android project needs to be gradle synced to get the latest Android SDK. Try updating all gradle dependencies by running this command from the directory `<project>/android`:
```
./gradlew build
```

**Comment by alyezz** [comment] 2019-03-28 15:29
Fixed in v8.2.1

**Closed** 2019-03-28 15:29 UTC
