### ISSUE TITLE
iOS Exception - TypeError: Cannot read property 'setShakingThresholdForiPhone' of undefined

### ISSUE THREAD

**Issue by jonczeck** [Instabug/Instabug-React-Native#412] opened 2019-09-26 21:03 UTC
Instabug crashes when setting shaking threshold.

### Steps to Reproduce the Problem

Follow manual install process. https://docs.instabug.com/docs/react-native-integration

### Expected Behavior
..Sets shaking threshold and doesn't throw an exception.

### Actual Behavior
Exception

### Instabug integration code
```
// Called from constructor
        const invocationEvents: Instabug.invocationEvent[] = [Instabug.invocationEvent.screenshot];
        if (isDevelopment === false) {
            // Only enable the shake gesture if we're not in debug mode, as it interferes with the shake gesture to bring up the React Native debug menu
            invocationEvents.push(Instabug.invocationEvent.shake);
        }
        Instabug.startWithToken('token', invocationEvents);
        Instabug.setColorTheme(Instabug.colorTheme.dark);
        BugReporting.setShakingThresholdForiPhone(2.5);

```

### SDK Version
8.7.0

### React Native, iOS and Android Versions
React Native: 0.59.10
iOS: 12.4.1

**Comment by AliAbdelfattah** [comment] 2019-10-07 10:34
Hi @jonczeck, sorry it took us a while to reply. Unfortunately, we're unable to reproduce it on our side. Would it be possible to upload a sample app where this issue is reproducible?

**Comment by jonczeck** [comment] 2019-10-11 16:51
I made a blank project and added Instabug to it, and it worked. I'm not sure what the difference is, so I give up on it.

**Comment by AliAbdelfattah** [comment] 2019-10-14 08:04
Closing this for now. Please feel free to reopen if you encounter it again.

**Closed by AliAbdelfattah** 2019-10-14 08:04 UTC
