### ISSUE TITLE
App crashes on launch and instabug is the cause

### ISSUE THREAD

**Issue by Etregoning** [Instabug/Instabug-React-Native#194] opened 2018-08-16 18:06 UTC
### Steps to Reproduce the Problem
Open the app

### Expected Behavior
App will run

### Actual Behavior
App crashes

### Instabug integration code
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
              new RNInstabugReactnativePackage.Builder("MY_TOKEN", MainApplication.this)
                      .setInvocationEvent("shake")
                      .build(),
          new RNFetchBlobPackage(),
          new VectorIconsPackage(),
          new SvgPackage()
      );
    }
  };
```

### SDK Version
Was using an older version (2.x.x), but I just updated the version because I was suspecting the old version was the cause. It was not. Current version is 8.0.9.

### React Native, iOS and Android Versions
Android only as far as I can tell, react version 16.0.0, react native version 0.48.3, Android target/compile sdk 26

### Device Model
Samsung Galaxy S9+

### Logcat info:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
        at android.graphics.Color.parseColor(Color.java:1384)
        at com.instabug.reactlibrary.RNInstabugReactnativePackage.<init>(RNInstabugReactnativePackage.java:51)
        at com.instabug.reactlibrary.RNInstabugReactnativePackage$Builder.build(RNInstabugReactnativePackage.java:142)
        at com.wildernesspatrol.MainApplication$1.getPackages(MainApplication.java:41)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:7174)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

```

I just started to notice crashing since I upgrade my phone to a Galaxy S9+, and I'm wondering if this error is specific to this device, and also wondering if the problem is on your end, is there a workaround for now?

Thanks!

**Comment by Etregoning** [comment] 2018-08-19 01:38
I have received an email from the Instabug support team about this issue, and apparently, they have fixed it in version 8.0.10, however, this version does not seem to be available to install yet. I will respond when it is and mark this issue as closed if it solves the problem.

**Comment by Etregoning** [comment] 2018-08-19 22:14
@salmatarzi Thanks, I have now installed the newest version in my project, however I am still having a minor issue, but I'm not yet sure if the problem is on my end or yours, because logcat isn't giving me any info about the crash this time.

Each time I build the app, the first launch crashes, but then after that I can load it up no problem, and Instabug works... I took a look at the migration guide, but my Java code seems to be right, and for React Native, it seems that instabug is pretty much fully contained in the Java files for Android, unlike iOS where it 's called from within the React code.

**Comment by Korazy** [comment] 2018-08-27 10:26
@Etregoning can you send us the stack trace of the error?

**Comment by Etregoning** [comment] 2018-08-27 11:28
That's the problem, logcat shows nothing this time. It compiles
successfully and there are no errors from react either. It was working fine
after the initial crash on build, but now it crashes every time I shake the
phone, for instabug

**Comment by Korazy** [comment] 2018-08-30 08:39
@Etregoning unfortunately, without a stacktrace it's difficult to resolve this issue since it's not reproducible on our end. Would you be able to try unlinking and linking again?

**Comment by Etregoning** [comment] 2018-08-31 03:37
Sorry, apparently I had something wrong with my Android studio at the time, but I have fixed that issue and this problem remains. I managed to get a stacktrace this time though.

The top of it says permission denied which makes me wonder what the issue could be, but I also see something in there about shake detector. It seems sometimes shaking it works, and sometimes shaking it crashes the app. It crashes 90% of the time on shake though.

I have given permission for overlay though, is it possible that I need to request additional permissions with the new version?

```
08-30 20:33:49.419 25420-25420/com.wildernesspatrol E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wildernesspatrol, PID: 25420
    android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@b4922e7 -- permission denied for window type 2003
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:981)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
        at android.app.Dialog.show(Dialog.java:420)
        at com.facebook.react.devsupport.DevSupportManagerImpl.showDevOptionsDialog(DevSupportManagerImpl.java:482)
        at com.facebook.react.devsupport.DevSupportManagerImpl$1.onShake(DevSupportManagerImpl.java:207)
        at com.facebook.react.common.ShakeDetector.maybeDispatchShake(ShakeDetector.java:149)
        at com.facebook.react.common.ShakeDetector.onSensorChanged(ShakeDetector.java:139)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:964)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by Korazy** [comment] 2018-09-02 22:47
Thanks for that, we're looking into it at the moment :)

**Comment by ramiimagdi** [comment] 2018-09-03 11:08
Hey Elliot, 
After looking deeper into the issue, this doesn't seem to be happening because of Instabug's shake gesture, but rather the shake gesture of React Native that triggers the dev menu. You can refer to this here:
https://stackoverflow.com/questions/32224452/android-unable-to-add-window-permission-denied-for-this-window-type

**Comment by Etregoning** [comment] 2018-09-03 22:53
It's still crashing on the initial build though, any word on that?

**Comment by Etregoning** [comment] 2018-10-16 08:32
@HeshamMegid it's okay, all that was available for a fix was a workaround, and since we were about to go live, I decided to build a less feature-rich bug reporting system to get us by, and I told this to support so I sorta stopped corresponding with the support team.

I do still really miss the instabug dashboard, and I definitely dont have time to build something like that, so I will give this a try tomorrow or the next day, as soon as I have time. We are trying to meet a November deadline for a client so we have been very busy.

I will let you know asap!

**Comment by HeshamMegid** [comment] 2018-10-16 08:42
That's great, best of luck! 🍀

**Comment by HeshamMegid** [comment] 2018-12-10 09:45
@Etregoning closing this for now. Please feel free to reopen when you get a chance to check it out.

**Closed by HeshamMegid** 2018-12-10 09:45 UTC
