### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException index=4 count=3 android.view.ViewGroup.addInArray (ViewGroup.java:5455)

### ISSUE THREAD

**Issue by AndrewMorsillo** [Instabug/Instabug-React-Native#515] opened 2020-09-16 19:25 UTC
This indexOutOfBoundsException only occurs when Instabug is integrated into my app. If I remove Instabug this issue goes away. 

This crashes 5-10% of end user sessions. Possibly related to https://github.com/Instabug/Instabug-React-Native/issues/514 ?

This only happens in our release build on the play store. 

```

Fatal Exception: java.lang.IndexOutOfBoundsException
index=4 count=3
android.view.ViewGroup.addInArray (ViewGroup.java:5455)
android.view.ViewGroup.addViewInner (ViewGroup.java:5348)
android.view.ViewGroup.addView (ViewGroup.java:5155)
com.facebook.react.views.view.ReactViewGroup.addView (ReactViewGroup.java:465)
android.view.ViewGroup.addView (ViewGroup.java:5095)
com.facebook.react.views.view.ReactClippingViewManager.addView (ReactClippingViewManager.java:38)
com.facebook.react.views.view.ReactClippingViewManager.addView (ReactClippingViewManager.java:19)
com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren (NativeViewHierarchyManager.java:507)
com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute (UIViewOperationQueue.java:209)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:917)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1028)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:48)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1088)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1055)
android.view.Choreographer.doCallbacks (Choreographer.java:875)
android.view.Choreographer.doFrame (Choreographer.java:772)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1042)
android.os.Handler.handleCallback (Handler.java:900)
android.os.Handler.dispatchMessage (Handler.java:103)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8347)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)

```

### Steps to Reproduce the Problem
Run a release build of a RN 0.63.2 app with Instabug on Android

### Expected Behavior
App should not crash

### Actual Behavior
App crashes randomly with the above exception for 5-10% of sessions. If we remove Instabug our app is 100% crash free.

### Instabug integration code
package.json
`"instabug-reactnative": "^9.1.7",`

MainApplication.java
```
import com.instabug.reactlibrary.RNInstabugReactnativePackage;
.....


  @Override
  public void onCreate() {
        .....

    new RNInstabugReactnativePackage.Builder("MY_TOKEN", MainApplication.this)
        .setInvocationEvent("shake")

        .setInvocationEvent("button").setPrimaryColor("#1D82DC").setFloatingEdge("right")
        .setFloatingButtonOffsetFromTop(500)
        .build();
    super.onCreate();
      .....
  }
```

App js code
```
  Instabug.startWithToken("MY_TOKEN", [Instabug.invocationEvent.shake])

        if (Platform.OS == "ios") {
            //only call this on ios, on android it results in two buttons
            let instabug_button_position = 0.55 * height
            Instabug.setFloatingButtonEdge(Instabug.floatingButtonEdge.right, instabug_button_position)
        }

        BugReporting.setAutoScreenRecordingEnabled(false)
```

### SDK Version
9.1.7 react native

### React Native, iOS and Android Versions
RN 0.63.2

### Device Model
Any Android device

### [Optional] Project That Reproduces the Issue
Unable to reproduce on demand. Only happens in release build on play store where it appears to happen at random.

**Comment by AliAbdelfattah** [comment] 2021-05-27 11:02
Closing this as we're not able to reproduce and the stack trace doesn't have any references to Instabug.

**Closed by AliAbdelfattah** 2021-05-27 11:02 UTC
