### ISSUE TITLE
Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException Trying to remove a view index above child count 8 view tag: 647

### ISSUE THREAD

**Issue by AndrewMorsillo** [Instabug/Instabug-React-Native#517] opened 2020-09-16 19:31 UTC
This IllegalViewOperationException only occurs when Instabug is integrated into my app. If I remove Instabug this issue goes away. 

Possibly related to https://github.com/Instabug/Instabug-React-Native/issues/515 ?

This only happens in our release build on the play store. 

```

Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException
Trying to remove a view index above child count 8 view tag: 647 detail: View tag:647 children(8): [ 625,643,677,695,777,849,917,925, ], indicesToRemove(1): [ 8, ], tagsToDelete(1): [ 937, ]
com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren (NativeViewHierarchyManager.java:411)
com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute (UIViewOperationQueue.java:209)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:917)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1028)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:48)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1088)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:965)
android.view.Choreographer.doCallbacks (Choreographer.java:791)
android.view.Choreographer.doFrame (Choreographer.java:722)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:952)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7356)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)

```

### Steps to Reproduce the Problem
Run a release build of a RN 0.63.2 app with Instabug on Android

### Expected Behavior
App should not crash

### Actual Behavior
App crashes randomly with the above exception. If we remove Instabug our app is 100% crash free.

### Instabug integration code
package.json
`"instabug-reactnative": "^9.1.7",`

MainApplication.java
```
import com.instabug.reactlibrary.RNInstabugReactnativePackage;
.....


  @Override
  public void onCreate() {
        .....

    new RNInstabugReactnativePackage.Builder("MY_TOKEN", MainApplication.this)
        .setInvocationEvent("shake")

        .setInvocationEvent("button").setPrimaryColor("#1D82DC").setFloatingEdge("right")
        .setFloatingButtonOffsetFromTop(500)
        .build();
    super.onCreate();
      .....
  }
```

App js code
```
  Instabug.startWithToken("MY_TOKEN", [Instabug.invocationEvent.shake])

        if (Platform.OS == "ios") {
            //only call this on ios, on android it results in two buttons
            let instabug_button_position = 0.55 * height
            Instabug.setFloatingButtonEdge(Instabug.floatingButtonEdge.right, instabug_button_position)
        }

        BugReporting.setAutoScreenRecordingEnabled(false)
```

### SDK Version
9.1.7 react native

### React Native, iOS and Android Versions
RN 0.63.2

### Device Model
Any Android device

### [Optional] Project That Reproduces the Issue
Unable to reproduce on demand. Only happens in release build on play store where it appears to happen at random.

**Comment by AliAbdelfattah** [comment] 2020-09-16 21:02
This doesn't seem to be related to our SDK, we don't do any UI manipulation in react native.

The information posted here may help https://github.com/facebook/react-native/issues/13984#issuecomment-301757346

**Comment by AndrewMorsillo** [comment] 2020-09-16 21:05
It certainly seems strange but I have verified that this issue _only_ happens when the Instabug react-native SDK is integrated into the app. I made two builds with the only change between them being removal of Instabug. Without Instabug this crash never happens. Perhaps related to `Instabug.setPrivateView(elem)`?

**Comment by AliAbdelfattah** [comment] 2020-09-16 21:34
Umm.. do you call that API anywhere in your app `setPrivateView`?

**Comment by AndrewMorsillo** [comment] 2020-09-17 12:21
Yes, we call it to mask some potentially personal information from user reports.

**Comment by AliAbdelfattah** [comment] 2021-05-27 11:01
Closing this as we're not able to reproduce and the stack trace doesn't have any references to Instabug.

**Closed by AliAbdelfattah** 2021-05-27 11:01 UTC
