### ISSUE TITLE
App hangs when calling startWithToken and then immediately calling console.log

### ISSUE THREAD

**Issue by vyrin** [Instabug/Instabug-React-Native#330] opened 2019-07-18 17:29 UTC
### Steps to Reproduce the Problem

Call Instabug.startWithToken
Soon afterwards call console.log()

Example code:

```
  constructor(props) {
    super(props);
    Instabug.startWithToken(TOKEN, [Instabug.invocationEvent.screenshot]);
    console.log("Test 1");
    console.log("Test 2");
    console.log("Test 3");
    console.log("Test 4");
    console.log("Test 5");
    console.log("Test 6");
    console.log("Test 7");
    console.log("Test 8");
    console.log("Test 9");
    console.log("Test 10");
  }

```
### Expected Behavior

Instabug starts as expected.

### Actual Behavior

The application hangs in the native layer.

In the case of the example code above the console will log:

```
2019-07-18 10:19:15.830 [info][tid:com.facebook.react.JavaScript] Test 1
2019-07-18 10:19:15.830 [info][tid:com.facebook.react.JavaScript] Test 2
2019-07-18 10:19:15.830 [info][tid:com.facebook.react.JavaScript] Test 3
2019-07-18 10:19:15.830 [info][tid:com.facebook.react.JavaScript] Test 4
2019-07-18 10:19:15.840 [info][tid:com.facebook.react.JavaScript] Test 5

```
And then hang.

### SDK Version

8.4.4 and 8.5.0

### React Native, iOS and Android Versions

RN 0.59.4
iOS 12.

### Theory and fix

This issue occurs due to a race condition on different threads.

In a recent code change, in InstabugReactBridge.m, the call to [Instabug startWithToken] was moved into a block that runs on the main thread.

But, immediately below that block the code calls: RCTAddLogFunction(InstabugReactLogFunction); on the current thread.

This means that any log messages that are sent by RN immediately afterwards get sent to InstabugReactLogFunction, and that can happen before the call to [Instabug startWithToken] actually happens on the main thread, and which in turn causes the app to hang.

If the call to RCTAddLogFunction(InstabugReactLogFunction); is instead moved into the main thread block immediately after [Instabug startWithToken] then everything works correctly.

Current code (InstabugReactBridge.m):

```
    [[NSRunLoop mainRunLoop] performBlock:^{
         [Instabug startWithToken:token invocationEvents:invocationEvents];
    }];

    RCTAddLogFunction(InstabugReactLogFunction);
    RCTSetLogThreshold(RCTLogLevelInfo);

```
Fixed code (InstabugReactBridge.m):

```
    [[NSRunLoop mainRunLoop] performBlock:^{
         [Instabug startWithToken:token invocationEvents:invocationEvents];
         RCTAddLogFunction(InstabugReactLogFunction);
    }];

    RCTSetLogThreshold(RCTLogLevelInfo);

```

**Comment by alyezz** [comment] 2019-07-20 07:36
@pbfrias17 thanks for reporting this. I was able to reproduce the issue and your theory seems to be correct. We'll include a fix in the next release.

**Comment by vyrin** [comment] 2019-07-20 16:47
Awesome. Thanks! We really enjoy using Instabug and appreciate how fast you respond to issues.

**Comment by alyezz** [comment] 2019-07-22 15:46
@vyrin We just release 8.5.1, this fix is included in there. Feel free to reopen this if the issue persists.

**Closed by alyezz** 2019-07-22 15:46 UTC
