### ISSUE TITLE
Instabug hijacking main thread on Modal open after Instabug 8.4.0

### ISSUE THREAD

**Issue by tedcurrent** [Instabug/Instabug-React-Native#370] opened 2019-08-22 10:44 UTC
Modal opens have started to lag since `instabug-react-native` 8.4.0. Reverting to 8.3.4 seems to fix the issue. Please see screenshots and videos below.

### Steps to Reproduce the Problem
1. Install `instabug-react-native` 8.4.0 or newer
2. Add a RN Modal with animation (easiest to use `react-native-modal`)
3. Open the modal

### Expected Behavior
Modal open should animate smoothly.

### Actual Behavior
Modal open animation lags (skips frames).

### SDK Version

`"instabug-reactnative": "8.5.4"`

### React Native, iOS and Android Versions
`"react-native": "0.60.4"`
iOS 12.4

### Device Model

iPhone X and iPhone XS at least.

### Diagnostics screenshots
Instabug 8.5.4 (poor perf)
![poor-perf](https://user-images.githubusercontent.com/7895034/63508313-66ed6e00-c4e2-11e9-8658-9a5bc7bdb534.png)

Instabug 8.3.4 (good perf)
![good-perf](https://user-images.githubusercontent.com/7895034/63508345-7371c680-c4e2-11e9-9e33-3fd046181dd7.png)

### Videos demonstrating both scenarios
[videos.zip](https://github.com/Instabug/Instabug-React-Native/files/3529690/videos.zip)

**Comment by AliAbdelfattah** [comment] 2019-08-24 01:08
Thank you for reporting this. We're looking into it.

**Comment by AliAbdelfattah** [comment] 2019-08-29 02:06
@tedcurrent, here’s an ad-hoc build of the SDK that has a different method of capturing screenshots for Repro Steps that solves the performance issue you’re facing. Please let us know how this build performs as we are currently testing it out before shipping it to production.

You can install it by running:
```sh
npm install --save https://github.com/Instabug/Instabug-React-Native#custom/repro-steps-ios-capture-fix
```

**Comment by tedcurrent** [comment] 2019-08-29 12:00
@AliAbdelfattah Thanks a lot! We'll get to testing this tomorrow! Superb :)

**Comment by tedcurrent** [comment] 2019-09-02 06:26
@AliAbdelfattah Alright I tested it properly this time. We can still see a slight ~60ms delay in the timing logs, which does cause a small jank, but it's definitely better. It's good to know that we can pinpoint it to repro steps, helps a ton!

Here's a comparison with the adhoc build

Adhoc build (Repro steps enabled):
![with-adhoc-build](https://user-images.githubusercontent.com/7895034/64093838-79796a00-cd62-11e9-9289-49da4bae42c7.png)

Adhoc build (Repro steps disabled):
![repro-disabled](https://user-images.githubusercontent.com/7895034/64093849-80a07800-cd62-11e9-9bb0-f54d796fb74f.png)

**Comment by HeshamMegid** [comment] 2019-09-02 09:21
@tedcurrent thanks a lot for testing it out and for the comparison. We're looking into ways to optimize this even more and for better support for Repro Steps on React Native. As a temporary workaround, you can disable Repro Steps for now.

I'll close this issue for now, but please feel free to reopen it if you need to discuss it more.

**Closed by HeshamMegid** 2019-09-02 09:21 UTC

**Comment by HeshamMegid** [comment] 2019-09-02 09:33
@tedcurrent actually, since we haven't been able to reproduce the slow performance you're getting, it would be really helpful if you could send us a dump of the view hierarchy of the view controller you're presenting that has the performance issue.

You can do this by pausing the Xcode debugger and typing `po [[UIWindow keyWindow] recursiveDescription]` into the console, or if you prefer, you can take a screenshot of Xcode's view hierarchy view.

**Comment by tedcurrent** [comment] 2019-09-04 06:30
@HeshamMegid thanks for committing time to this! 

See view hierarchy dump here:
[logs.txt](https://github.com/Instabug/Instabug-React-Native/files/3572983/logs.txt)

I also noticed from the console that we get this on each modal open:
```
Instabug: Capture CustomView.
Instabug: Capture CustomView.
Instabug: Capture CustomView.
Instabug: Capture CustomView.
Instabug: Capture CustomView.
```
So 5 logs on each modal open. This seems to pop up on modals only. Other views don't show such logs.

**Comment by HeshamMegid** [comment] 2019-09-04 09:10
@tedcurrent thank you so much! We'll be looking into why this specific view hierarchy is taking a long time to be captured.
