### ISSUE TITLE
InstabugCore is not found

### ISSUE THREAD

**Issue by sebirdman** [Instabug/Instabug-React-Native#184] opened 2018-08-02 17:26 UTC
Trying to update from 8.0.0 to 8.0.4

node_modules/instabug-reactnative/ios/InstabugCore.framework: No such file or directory

Indeed, the file does not seem to be there anymore. Do we still need it? The current docs for manual linking still contain this: https://docs.instabug.com/docs/react-native-integration

**Comment by sebirdman** [comment] 2018-08-02 17:36
After removing all mentions of InstabugCore from my xcode build, everything seems to be working fine...

**Comment by MattyK14** [comment] 2018-08-03 14:54
I had no success removing all the references to `InstabugCore`, reverted to version `8.0.1`.

**Comment by Korazy** [comment] 2018-08-05 12:13
Hey all, 

Thanks for reaching out. This issue should be resolved by following the steps [here](https://github.com/Instabug/instabug-reactnative#upgrading-from-20x-and-from-803).

**Comment by FloSugar** [comment] 2018-08-08 15:08
Hey, got the same problem and above solution is not working.

**Comment by Korazy** [comment] 2018-08-14 20:42
Hey @MattyK14 @sebirdman 

Were you able to fix the issue?

**Comment by matteodanelli** [comment] 2018-08-16 10:30
@Korazy I followed guidelines (unlink and then link) but no success. I have same problem..

**Comment by Korazy** [comment] 2018-08-16 12:30
@matteodanelli would you be able to tell me which step the error occurs in?

**Comment by matteodanelli** [comment] 2018-08-16 12:34
Sure. I've version 2.13.3 and want to upgrade to 8.0.8, the latest.
I've done the following steps:

- react-native unlink instabug-reactnative
- yarn add instabug-reactnative
- react-native link instabug-reactnative
- react-native run-ios

And the build fail with the errore **Instacore not found**.

**Comment by Korazy** [comment] 2018-08-16 12:55
@matteodanelli Would you be able to give this sample app a go and let me know if you have the same build fail with it?
[SampleApp.zip](https://github.com/Instabug/Instabug-React-Native/files/2293734/SampleApp.zip)

**Comment by matteodanelli** [comment] 2018-08-16 13:50
This works well, but I think the problem is somewhat related to switching from version 2 to version 8.. I even tried to remove instabug completely and installed 8 but seems not works.

**Comment by Korazy** [comment] 2018-08-17 23:35
@matteodanelli unfortunately we're having a hard time reproducing this issue. Would it be possible to send us a sample app containing this particular bug?

**Comment by rpstew** [comment] 2018-08-20 22:39
I had a similar issue that I just solved.  The one file I'm assuming is causing you the issue is ios/<AppName>.xcodeproj/project.pbxproj

Our version of that file had references to InstabugCore.framework.  I don't remember the exact step I did to update that file, but the issue went away after the update.

**Comment by matteodanelli** [comment] 2018-08-22 08:49
Thanks. I solved.
I removed every reference of _InstabugCore.framework_ from _project.pbxproj_.

**Comment by Korazy** [comment] 2018-08-27 10:10
awesome, im happy to hear that everything is fine now.

**Closed by Korazy** 2018-08-27 10:10 UTC
